language: node_js

node_js:
  - 10.8

cache:
  directories:
    - ~/.npm
    - ~/.cache

before_script: cd apioarchitect.com

script:
  - npm install
  - npm run build
  - npm run serve & npm run wait-on http://localhost:8000
  - npm run cy:run:record
  - kill $(jobs -p) || true